import axios from "axios";

const BASEURL = "http://fakestoreapi.com" ;
axios.defaults.baseURL = BASEURL ; 

const getProducts = async() => {
    // const response = await axios.get("/products");
    return [
    {
        id:1,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
    {
        id:2,
        title : "dummy" ,
        description : "dummy" ,
        price : "5" ,
        category : "dummy" ,
        image : "dummy" ,
    } ,
] ;
}

export {getProducts} ;